name: api-deploy-portal-dev

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      RUNS_ON:
        type: string
        default: ubuntu-latest

    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true

      AWS_ACCESS_KEY_ID_DEV:
        required: true
      AWS_SECRET_ACCESS_KEY_DEV:
        required: true
      AWS_REGION_DEV:
        required: true

      DATABASE_HOST_DEV:
        required: false
      DATABASE_USERNAME_DEV:
        required: false
      DATABASE_PASSWORD_DEV:
        required: false
      DATABASE_NAME_DEV:
        required: false

      NAVEGA_API_URL_DEV:
        required: false

      DD_API_KEY:
        required: true
      LOG_LEVEL_DEV:
        required: true
      ENV_DEV:
        required: true

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ${{ inputs.RUNS_ON }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST_DEV}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_DEV}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_DEV}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_DEV}}

      NAVEGA_API_URL: ${{secrets.NAVEGA_API_URL_DEV}}
      NAVEGA_PORTAL_API_URL: ${{secrets.NAVEGA_PORTAL_API_URL_DEV}}

      SIMULATION_API_URL: ${secrets.SIMULATION_API_URL_DEV}

      LOG_LEVEL: ${{secrets.LOG_LEVEL_DEV}}
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      ENV: ${{secrets.ENV_DEV}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Jfrog
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"

      - name: Install & Build Libs
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          sh ../build-libs.sh

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn install

      - name: Development Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID_DEV}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
          export AWS_REGION=${{secrets.AWS_REGION_DEV}}
          npm i -g serverless
          sls deploy --stage ${{secrets.ENV_DEV}} --region $AWS_REGION
