name: api-deploy-prd

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      RUNS_ON:
        type: string
        default: ubuntu-latest

    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true

      AWS_ACCESS_KEY_ID_PRD:
        required: true
      AWS_SECRET_ACCESS_KEY_PRD:
        required: true
      AWS_REGION_PRD:
        required: true

      SUBNET_APP_A_PRD:
        required: true
      SUBNET_APP_B_PRD:
        required: true
      SECURITY_GROUP_API_PRD:
        required: true

      ENV_PRD:
        required: true
      LOG_LEVEL_PRD:
        required: true
      DD_API_KEY:
        required: true

      NAVEGA_API_URL_PRD:
        required: false

      DATABASE_HOST_PRD:
        required: false
      DATABASE_USERNAME_PRD:
        required: false
      DATABASE_PASSWORD_PRD:
        required: false
      DATABASE_NAME_PRD:
        required: false

      KEYCLOAK_URL_PRD:
        required: false
      KEYCLOAK_USERNAME_ADMIN_PRD:
        required: false
      KEYCLOAK_PASSWORD_ADMIN_PRD:
        required: false

      AWS_DYNAMODB_REGION_PRD:
        required: false
      AWS_DYNAMODB_VERSION_PRD:
        required: false
      AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE_PRD:
        required: false

      USE_WRITE_COMMAND_WITH_QUEUE_PRD:
        required: false
      WRITE_COMMAND_MESSAGE_BATCH_SIZE_PRD:
        required: false

      # env MAX_OUTPUT_DATA_SIZE_IN_MB utilizada no workflows-api, para limitar o tamanho do output maximo a ser retornado
      # limitamos ele em uma tamanho menor, pois a ideia é q o output limitado, seja utilizado mais pelo front
      # dessa maneira o tamanho do output é limitado a 1MB, q ja é bastante informação para ser exibida
      MAX_OUTPUT_DATA_SIZE_IN_MB:
        required: false

      # env RULES_API_MAX_OUTPUT_DATA_SIZE_IN_MB é similar ao MAX_OUTPUT_DATA_SIZE_IN_MB, mas quem utilizará esse endpoint
      # serão os backend, com os resultados dos processos, por isso o tamanho do output é maior
      RULES_API_MAX_OUTPUT_DATA_SIZE_IN_MB:
        required: false
      TIMEOUT_TASK_EXECUTION_IN_SECONDS:
        required: false
      FREE_MEMORY_LIMIT_IN_MB:
        required: false

      MFA_KEY_PRD:
        required: false

      NAVEGA_API_REPORT_USERNAME:
        required: false
      NAVEGA_API_REPORT_PASSWORD:
        required: false
jobs:
  deploy-prd:
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ inputs.RUNS_ON }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_HOST: ${{vars.DATABASE_HOST_PRD}}
      DATABASE_USERNAME: ${{vars.DATABASE_USERNAME_PRD}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_PRD}}
      DATABASE_NAME: ${{vars.DATABASE_NAME_PRD}}

      DATABASE_DATA_SOURCE: ${{ vars.DATABASE_DATA_SOURCE_PRD }}
      DATABASE_API_URL: ${{ vars.DATABASE_API_URL }}
      DATABASE_API_KEY: ${{ secrets.DATABASE_API_KEY_PRD }}

      KEYCLOAK_URL: ${{vars.KEYCLOAK_URL_PRD}}
      KEYCLOAK_USERNAME_ADMIN: ${{vars.KEYCLOAK_USERNAME_ADMIN_PRD}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_PRD}}

      SUBNET_APP_A: ${{vars.SUBNET_APP_A_PRD}}
      SUBNET_APP_B: ${{vars.SUBNET_APP_B_PRD}}
      SECURITY_GROUP_API: ${{vars.SECURITY_GROUP_API_PRD}}

      LOG_LEVEL: ${{vars.LOG_LEVEL_PRD}}
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      ENV: ${{vars.ENV_PRD}}

      NAVEGA_API_URL: ${{vars.NAVEGA_API_URL_PRD}}

      AWS_DYNAMODB_REGION: ${{vars.AWS_REGION_PRD}}
      AWS_DYNAMODB_VERSION: ${{vars.AWS_DYNAMODB_VERSION_PRD}}
      AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE: ${{vars.AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE_PRD}}

      EMAIL_PROVIDER: ${{ vars.EMAIL_PROVIDER_PRD }}
      EMAIL_USERNAME: ${{ vars.EMAIL_USERNAME_PRD }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_PRD }}

      USE_WRITE_COMMAND_WITH_QUEUE: ${{ vars.USE_WRITE_COMMAND_WITH_QUEUE_PRD }}
      WRITE_COMMAND_MESSAGE_BATCH_SIZE: ${{ vars.WRITE_COMMAND_MESSAGE_BATCH_SIZE_PRD }}

      USE_ATLAS_API_REQUEST: ${{ vars.USE_ATLAS_API_REQUEST }}

      MAX_OUTPUT_DATA_SIZE_IN_MB: ${{ vars.MAX_OUTPUT_DATA_SIZE_IN_MB }}
      RULES_API_MAX_OUTPUT_DATA_SIZE_IN_MB: ${{ vars.RULES_API_MAX_OUTPUT_DATA_SIZE_IN_MB }}
      TIMEOUT_TASK_EXECUTION_IN_SECONDS: ${{ vars.TIMEOUT_TASK_EXECUTION_IN_SECONDS}}
      FREE_MEMORY_LIMIT_IN_MB: ${{ vars.FREE_MEMORY_LIMIT_IN_MB}}

      CF_DISTRIBUTION_NAVEGA: ${{ vars.CF_DISTRIBUTION_NAVEGA_PRD }}
      INTEGRATION_API_URL: ${{ vars.INTEGRATION_API_URL_PRD }}

      MFA_KEY: ${{ secrets.MFA_KEY_PRD }}

      NAVEGA_API_REPORT_USERNAME: ${{ vars.NAVEGA_API_REPORT_USERNAME }}
      NAVEGA_API_REPORT_PASSWORD: ${{ secrets.NAVEGA_API_REPORT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{vars.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '//f3capital.jfrog.io/artifactory/api/npm/f3capital-npm/:_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{vars.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          
          # Install dependencies in the root directory
          if [ -f "package.json" ]; then
            yarn install
          fi

          # Install dependencies in subdirectories of 'layer'
          if [ -d "layer" ]; then
            for dir in layer/*/; do
              if [ -f "$dir/package.json" ]; then
                (cd "$dir" && yarn install)
              fi
            done
          fi

      - name: Production Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          export VERSION=$(node -p "require('./package.json').version")
          export AWS_ACCESS_KEY_ID=${{vars.AWS_ACCESS_KEY_ID_PRD}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_PRD}}
          export AWS_REGION=${{vars.AWS_REGION_PRD}}
          npm i -g serverless@3
          sls deploy --stage ${{vars.ENV_PRD}} --region $AWS_REGION
