name: api-deploy-portal-sbx

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      RUNS_ON:
        type: string
        default: ubuntu-latest

    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true

      AWS_ACCESS_KEY_ID_SBX:
        required: true
      AWS_SECRET_ACCESS_KEY_SBX:
        required: true
      AWS_REGION_SBX:
        required: true

      DATABASE_HOST_SBX:
        required: false
      DATABASE_USERNAME_SBX:
        required: false
      DATABASE_PASSWORD_SBX:
        required: false
      DATABASE_NAME_SBX:
        required: false

      NAVEGA_API_URL_SBX:
        required: false

      ENV_SBX:
        required: true
      LOG_LEVEL_SBX:
        required: true
      DD_API_KEY:
        required: true

jobs:
  deploy-sbx:
    if: github.ref == 'refs/heads/sbx'
    runs-on: ${{ inputs.RUNS_ON }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST_SBX}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_SBX}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_SBX}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_SBX}}

      NAVEGA_API_URL: ${{secrets.NAVEGA_API_URL_SBX}}
      NAVEGA_PORTAL_API_URL: ${{secrets.NAVEGA_PORTAL_API_URL_SBX}}

      SIMULATION_API_URL: ${{secrets.SIMULATION_API_URL_DEV}}

      SUBNET_APP_A: ${{secrets.SUBNET_APP_A_SBX}}
      SUBNET_APP_B: ${{secrets.SUBNET_APP_B_SBX}}
      SECURITY_GROUP_API: ${{secrets.SECURITY_GROUP_API_SBX}}

      LOG_LEVEL: ${{secrets.LOG_LEVEL_SBX}}
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      ENV: ${{secrets.ENV_SBX}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Jfrog
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"

      - name: Install & Build Libs
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          sh ../build-libs.sh

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn install

      - name: Sandbox Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID_SBX}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_SBX}}
          export AWS_REGION=${{secrets.AWS_REGION_SBX}}
          npm i -g serverless
          sls deploy --stage ${{secrets.ENV_SBX}} --region $AWS_REGION
