name: api-deploy-sbx

on:
  workflow_call:
    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true
      AZURE_SUBSCRIPTION_ID: 
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_FUNCTIONS_APP_ID:
        required: true
      AZURE_FUNCTIONS_SECRET:
        required: true
      AZURE_REGION_SBX:
        required: true
      AZURE_RESOURCE_GROUP_SBX:
        required: true
        
      AWS_ACCESS_KEY_ID_SBX:
        required: false
      AWS_SECRET_ACCESS_KEY_SBX:
        required: false
      AWS_REGION_SBX:
        required: false

      ENV_SBX:
        required: true

      DATABASE_HOST_SBX:
        required: true
      DATABASE_USERNAME_SBX:
        required: true
      DATABASE_PASSWORD_SBX:
        required: true
      DATABASE_NAME_SBX:
        required: true

      EMAIL_PROVIDER_DEV:
        required: false
      EMAIL_USERNAME_DEV:
        required: false
      EMAIL_PASSWORD_DEV:
        required: false

      KEYCLOAK_URL_SBX:
        required: false
      KEYCLOAK_USERNAME_ADMIN_SBX:
        required: false
      KEYCLOAK_PASSWORD_ADMIN_SBX:
        required: false
      
      EVENTBUS_NAME:
        required: false
      EVENTBUS_SOURCE:
        required: false
      EVENTBUS_DETAIL_TYPE:
        required: false
        
      NAVEGA_API_URL_SBX:
        required: false

jobs:
  deploy-sbx:
    if: github.ref == 'refs/heads/sbx'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      AZURE_REGION: ${{secrets.AZURE_REGION_SBX}}
      AZURE_STAGE: ${{secrets.ENV_SBX}}
      AZURE_RESOURCE_GROUP: ${{secrets.AZURE_RESOURCE_GROUP_SBX}}

      DATABASE_HOST: ${{secrets.DATABASE_HOST_SBX}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_SBX}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_SBX}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_SBX}}
      
      EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER_DEV }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_DEV }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_DEV }}
      
      KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL_SBX}}
      KEYCLOAK_USERNAME_ADMIN: ${{secrets.KEYCLOAK_USERNAME_ADMIN_SBX}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_SBX}}
      
      EVENTBUS_NAME: ${{ secrets.EVENTBUS_NAME }}
      EVENTBUS_REGION: ${{ secrets.AWS_REGION_SBX }}
      EVENTBUS_SOURCE: ${{ secrets.EVENTBUS_SOURCE }}
      EVENTBUS_DETAIL_TYPE: ${{ secrets.EVENTBUS_DETAIL_TYPE }}
      EVENTBUS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
      EVENTBUS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
      
      NAVEGA_API_URL: ${{ secrets.NAVEGA_API_URL_SBX }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install
      
      - name: Sandbox Deploy
        run: |
          export APP_NAME=$(node -p "require('./package.json').name")
          sls package
          az login --service-principal --username ${{secrets.AZURE_FUNCTIONS_APP_ID}} --password ${{secrets.AZURE_FUNCTIONS_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_SBX}} -n aquario-eus2-sbx-$APP_NAME --src .serverless/$APP_NAME.zip
          sls deploy
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_SBX}} -n aquario-eus2-sbx-$APP_NAME --src .serverless/$APP_NAME.zip
