name: lib-deploy-main

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
jobs:
  deploy-lib:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/RMD-BETA'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install      
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '//f3capital.jfrog.io/artifactory/api/npm/f3capital-npm/:_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          yarn install
      
      - name: Build 
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn build

      - name: Deploy Lib
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          
      - run: |
          cd ${{ inputs.WORKING_DIRECTORY }}
          jf --v
          jf c add f3capital --artifactory-url=${{secrets.ARTIFACTORY_URL}} --user=${{secrets.ARTIFACTORY_USER}} --password=${{secrets.ARTIFACTORY_PASSWORD}} --interactive=false
          jf c show
          jf npmc --server-id-resolve=f3capital --repo-resolve=${{secrets.ARTIFACTORY_NPM_REPOSITORY}} --server-id-deploy=f3capital --repo-deploy=${{secrets.ARTIFACTORY_NPM_REPOSITORY}}
          export BUILD_NAME=$(node -p "require('./package.json').name")
          export BUILD_VERSION=$(node -p "require('./package.json').version")
          jf npm install --build-name=$BUILD_NAME --build-number=$BUILD_VERSION
          jf rt bce $BUILD_NAME $BUILD_VERSION
          jf npm publish --build-name=$BUILD_NAME --build-number=$BUILD_VERSION
