name: lib-monorepo-deploy-main

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      LIB_NAME:
        type: string
jobs:
  deploy-lib:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/RMD-BETA'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set JFrog NPM Registry
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '//f3capital.jfrog.io/artifactory/api/npm/f3capital-npm/:_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc

      - name: Setup Core
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          cd ../core
          yarn
          yarn build

      - name: Setup Lib
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn
          yarn build

      - name: Deploy Lib
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          cd ${{ inputs.WORKING_DIRECTORY }}
          jf c add f3capital --artifactory-url=${{secrets.ARTIFACTORY_URL}} --user=${{secrets.ARTIFACTORY_USER}} --password=${{secrets.ARTIFACTORY_PASSWORD}} --interactive=false
          jf npmc --server-id-resolve=f3capital --repo-resolve=${{secrets.ARTIFACTORY_NPM_REPOSITORY}} --server-id-deploy=f3capital --repo-deploy=${{secrets.ARTIFACTORY_NPM_REPOSITORY}}
          export BUILD_NAME=$(node -p "require('./package.json').name")
          export BUILD_VERSION=$(node -p "require('./package.json').version")
          jf npm install --build-name=$BUILD_NAME --build-number=$BUILD_VERSION          
          jf rt bce $BUILD_NAME $BUILD_VERSION
          jf npm publish --build-name=$BUILD_NAME --build-number=$BUILD_VERSION
