name: lib-release-notes

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr list --base main --state merged --json title,url,author,mergedAt --jq '.[] | {title, url, author: .author.login, mergedAt: .mergedAt}' > prs.json
          echo "::set-output name=prs::$(cat prs.json)"          
