name: lib-release-notes

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr list --base main --state merged
