name: lib-deploy-main

on:
  workflow_call:
  
jobs:
  deploy-lib:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          yarn install
      
      - name: Build 
        run: |
          yarn build

      - name: Deploy Lib
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          jf --v
          jf c add f3capital --artifactory-url=${{secrets.ARTIFACTORY_URL}} --user=${{secrets.ARTIFACTORY_USER}} --password=${{secrets.ARTIFACTORY_PASSWORD}} --interactive=false
          jf c show
          jf npmc --server-id-resolve=f3capital --repo-resolve=${{secrets.ARTIFACTORY_NPM_REPOSITORY}} --server-id-deploy=f3capital --repo-deploy=${{secrets.ARTIFACTORY_NPM_REPOSITORY}}
          export BUILD_NAME=$(node -p "require('./package.json').name")
          export BUILD_VERSION=$(node -p "require('./package.json').version")
          npm config fix
          jf npm install ${{secrets.ARTIFACTORY_NPM_REPOSITORY}} --build-name=$BUILD_NAME --build-number=$BUILD_VERSION
          jf rt bce $BUILD_NAME $BUILD_VERSION
          jf npm publish ${{secrets.ARTIFACTORY_NPM_REPOSITORY}} --build-name=$BUILD_NAME --build-number=$BUILD_VERSION
