name: monorepo-api-deploy-prd

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      RUNS_ON:
        type: string
        default: ubuntu-latest
    secrets:
      ARTIFACTORY_AUTH:
        required: true
      AWS_SECRET_ACCESS_KEY_PRD:
        required: true
      DATABASE_PASSWORD_PRD:
        required: false
      DD_API_KEY:
        required: true
      KEYCLOAK_PASSWORD_ADMIN_PRD:
        required: false
jobs:
  deploy-prd:
    if: github.ref == 'refs/heads/prd'
    runs-on: ${{ inputs.RUNS_ON }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_HOST: ${{vars.DATABASE_HOST_PRD}}
      DATABASE_USERNAME: ${{vars.DATABASE_USERNAME_PRD}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_PRD}}
      DATABASE_NAME: ${{vars.DATABASE_NAME_PRD}}

      KEYCLOAK_URL: ${{vars.KEYCLOAK_URL_PRD}}
      KEYCLOAK_USERNAME_ADMIN: ${{vars.KEYCLOAK_USERNAME_ADMIN_PRD}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_PRD}}

      SUBNET_APP_A: ${{vars.SUBNET_APP_A_PRD}}
      SUBNET_APP_B: ${{vars.SUBNET_APP_B_PRD}}
      SECURITY_GROUP_API: ${{vars.SECURITY_GROUP_API_PRD}}

      NAVEGA_API_URL: ${{vars.NAVEGA_API_URL_PRD}}

      LOG_LEVEL: ${{vars.LOG_LEVEL_PRD}}
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      ENV: ${{vars.ENV_PRD}}

      AWS_DYNAMODB_REGION: ${{vars.AWS_REGION_PRD}}
      AWS_DYNAMODB_VERSION: ${{vars.AWS_DYNAMODB_VERSION_PRD}}
      AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE: ${{vars.AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE_PRD}}

      EMAIL_PROVIDER: ${{ vars.EMAIL_PROVIDER_PRD }}
      EMAIL_USERNAME: ${{ vars.EMAIL_USERNAME_PRD }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_PRD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          cd ..
          npm config set registry ${{vars.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '//f3capital.jfrog.io/artifactory/api/npm/f3capital-npm/:_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{vars.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          cp ~/.npmrc ./.npmrc
          yarn install
          yarn build

      - name: Production Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          export VERSION=$(node -p "require('./package.json').version")
          export AWS_ACCESS_KEY_ID=${{vars.AWS_ACCESS_KEY_ID_PRD}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_PRD}}
          export AWS_REGION=${{vars.AWS_REGION_PRD}}
          npm i -g serverless@3
          sls deploy --stage ${{vars.ENV_PRD}} --region $AWS_REGION
