name: web-deploy-stg

on:
  workflow_call:

jobs:
  deploy-stg:
    if: github.ref == 'refs/heads/stg'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:
      API_URL: ${{secrets.NAVEGA_API_URL_STG}}
      DATADOG_CLIENT_TOKEN: ${{secrets.DATADOG_CLIENT_TOKEN_STG}}
      DATADOG_APPLICATION_ID: ${{secrets.DATADOG_APPLICATION_ID_STG}}
      DATADOG_SAMPLE_RATE: ${{secrets.DATADOG_SAMPLE_RATE_STG}}
      DATADOG_SERVICE: navega-web-stg
      DATADOG_ENV: stg
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install

      - name: Build
        run: |
          yarn build
      
      - name: Staging Deploy
        run: |
          az storage blob delete-batch -s "\$web" --connection-string "${{secrets.AZURE_STORAGE_STG}}"
          az storage blob upload-batch -d "\$web" -s dist --connection-string "${{secrets.AZURE_STORAGE_STG}}"
          az login --service-principal --username ${{secrets.AZURE_FRONT_DOOR_APP_ID}} --password ${{secrets.AZURE_FRONT_DOOR_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az afd endpoint purge -g ${{secrets.AZURE_NETWORK_RG_STG}} --profile-name ${{secrets.AZURE_FRONT_DOOR_NAME_STG}} --endpoint-name ${{secrets.AZURE_FRONT_DOOR_ENDPOINT_NAME_STG}} --content-paths '/*'
