name: web-deploy-sbx

on:
  workflow_call:

jobs:
  deploy-sbx:
    if: github.ref == 'refs/heads/sbx'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:
      API_URL: ${{secrets.NAVEGA_API_URL_SBX}}
      DATADOG_CLIENT_TOKEN: ${{secrets.DATADOG_CLIENT_TOKEN_SBX}}
      DATADOG_APPLICATION_ID: ${{secrets.DATADOG_APPLICATION_ID_SBX}}
      DATADOG_SAMPLE_RATE: ${{secrets.DATADOG_SAMPLE_RATE_SBX}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install

      - name: Build
        run: |
          yarn build
      
      - name: Sandbox Deploy
        run: |
          az storage blob delete-batch -s "\$web" --connection-string "${{secrets.AZURE_STORAGE_SBX}}"
          az storage blob upload-batch -d "\$web" -s dist --connection-string "${{secrets.AZURE_STORAGE_SBX}}"
          az login --service-principal --username ${{secrets.AZURE_FRONT_DOOR_APP_ID}} --password ${{secrets.AZURE_FRONT_DOOR_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az afd endpoint purge -g ${{secrets.AZURE_NETWORK_RG_SBX}} --profile-name ${{secrets.AZURE_FRONT_DOOR_NAME_SBX}} --endpoint-name ${{secrets.AZURE_FRONT_DOOR_ENDPOINT_NAME_SBX}} --content-paths '/*'
