name: web-deploy-sbx

on:
  workflow_call:

jobs:
  deploy-sbx:
    if: github.ref == 'refs/heads/sbx'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:
      API_URL: ${{vars.NAVEGA_API_URL_SBX}}
      DATADOG_CLIENT_TOKEN: ${{secrets.DATADOG_CLIENT_TOKEN_SBX}}
      DATADOG_APPLICATION_ID: ${{vars.DATADOG_APPLICATION_ID_SBX}}
      DATADOG_SAMPLE_RATE: ${{vars.DATADOG_SAMPLE_RATE_SBX}}
      DATADOG_SERVICE: navega-web-sbx
      DATADOG_ENV: sbx

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install
        run: |
          npm config set registry ${{vars.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{vars.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          yarn install

      - name: Build
        run: |
          yarn build
      
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID_SBX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
          aws-region: ${{ vars.AWS_REGION_SBX }}

      - name: Sandbox Deploy AWS
        run: |
          aws s3 sync dist/ s3://sbx.navega.com.vc --delete
          aws cloudfront create-invalidation --distribution-id=E2KSPEOA8VYOAU --paths "/*"
