name: web-deploy-aws-dev

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      BUCKET_PATH:
        type: string
        required: true

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install

      - name: Build
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn build

      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Development Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          aws s3 sync dist/ s3://${{inputs.BUCKET_PATH}} --delete
          aws cloudfront create-invalidation --distribution-id=ERYU3DLSLHXC3 --paths /
