name: web-deploy-prd

on:
  workflow_call:

jobs:
  deploy-prd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      API_URL: ${{vars.NAVEGA_API_URL_PRD}}
      LOAN_API_URL: ${{vars.LOAN_API_URL_PRD}}
      DATADOG_CLIENT_TOKEN: ${{secrets.DATADOG_CLIENT_TOKEN_PRD}}
      DATADOG_APPLICATION_ID: ${{vars.DATADOG_APPLICATION_ID_PRD}}
      DATADOG_SAMPLE_RATE: ${{vars.DATADOG_SAMPLE_RATE_PRD}}
      DATADOG_SERVICE: navega-web-prd
      DATADOG_ENV: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17

      - name: Install
        run: |
          npm config set registry ${{vars.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{vars.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID_PRD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
          aws-region: ${{ vars.AWS_REGION_PRD }}

      - name: Production Deploy AWS
        run: |
          aws s3 sync dist/ s3://navega.com.vc --delete
          aws cloudfront create-invalidation --distribution-id=E1F33R6KRNBSDL --paths "/*"
