name: web-deploy-aws-dev

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      BUCKET_PATH:
        type: string
        required: true

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:
      PORTAL_SHELL_MANIFEST: ${{ secrets.PORTAL_BASE_URL_DEV }}/assets/mf.manifest.json
      PORTAL_API_URL: ${{ secrets.NAVEGA_PORTAL_API_URL_DEV }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Jfrog
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc
        
      - name: Install & Build Commons
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          cd ../libs/navega-portal-common && yarn install && yarn build
          
      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn install

      - name: Build
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn dev

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Development Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          aws s3 sync dist/ s3://${{inputs.BUCKET_PATH}} --delete
          aws cloudfront create-invalidation --distribution-id=ERYU3DLSLHXC3 --paths "/*"
