name: web-deploy-portal-stg

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
      BUCKET_PATH:
        type: string
        required: true

jobs:
  deploy-stg:
    if: github.ref == 'refs/heads/stg'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      PORTAL_SHELL_MANIFEST: /assets/mf.manifest.json
      PORTAL_API_URL: ${{ secrets.NAVEGA_PORTAL_API_URL_STG }}
      DATADOG_APPLICATION_ID: ${{ secrets.DD_NAVEGA_PORTAL_APPLICATION_ID_STG }}
      DATADOG_CLIENT_TOKEN: ${{ secrets.DD_NAVEGA_PORTAL_CLIENT_TOKEN_STG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Jfrog
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '//f3capital.jfrog.io/artifactory/api/npm/f3capital-npm/:_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          echo "always-auth=true" >> ~/.npmrc

      - name: Install & Build Commons
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          cd ../libs/navega-portal-common && yarn install && yarn build

      - name: Install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn install

      - name: Build
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          yarn build

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
          aws-region: ${{ secrets.AWS_REGION_STG }}

      - name: Staging Deploy
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          aws s3 sync dist/ s3://${{inputs.BUCKET_PATH}} --delete
          aws cloudfront create-invalidation --distribution-id=E1XRBL09UFC26B --paths "/*"
